namespace: 'test'

replicaCount: 1

image:
  name: 'nginx'
  tag: '1.14.2'

container:
  port: 80

pv_1:
  name: 'one'
  driver: 'file.csi.azure.com'
  storage: '3Gi'
  mountPath: '/mnt/one'
  shareName: 'share-one'
  storageRg:
  accessModes: 'ReadOnlyMany'
  storageClassName: 'azurefile-csi'
  storageAccountKeySecretNs: 'default'
  storageAccountKeySecretName: 'storage-account-key-secret'